import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        background: "#faf8ff",
        "on-background": "#1a1b23",
        "on-surface": "#1a1b23",
        "on-surface-variant": "#434655",
        "surface-variant": "#e2e1ed",
        "surface-container": "#ededf9",
        "surface-container-low": "#f3f2fe",
        "surface-container-high": "#e8e7f3",
        "surface-container-highest": "#e2e1ed",
        "surface-dim": "#d9d9e5",
        "surface-bright": "#faf8ff",
        "surface-tint": "#2151da",
        "inverse-surface": "#2e3039",
        "inverse-on-surface": "#f0f0fb",
        primary: "#0037b0",
        "primary-container": "#1d4ed8",
        "on-primary": "#ffffff",
        "on-primary-container": "#cad3ff",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b7c4ff",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#0039b5",
        "inverse-primary": "#b7c4ff",
        secondary: "#565e74",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        tertiary: "#7f2500",
        "tertiary-container": "#a73400",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffc9b7",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#832700",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#747686",
        "outline-variant": "#c4c5d7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
        h1: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        h2: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        h3: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        label: [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        h2: [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        h1: [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
